### ISSUE TITLE
Optimization Process

### ISSUE THREAD

**Issue by markusobi0** [opentelekomcloud-docs/image-management-service#46]
Issue on page:        https://github.com/opentelekomcloud-docs/image-management-service/blob/main/umn/source/managing_private_images/optimizing_a_windows_private_image/optimization_process.rst

Here we are talking about Xen. However, Xen Flavors are no longer available in the OTC.

**Comment by vladimirhasko** [comment]
thanks for spotting this discrepancy.
We address it with our internal ticket system and fix will be provided soon

**Comment by vladimirhasko** [comment]
documentation fixed
