### ISSUE TITLE
broken URL

### ISSUE THREAD

**Issue by Thies76** [opentelekomcloud-docs/image-management-service#76]
Hi team,

there is a broken URL on this page. Could you please fix it.

Issue on page:        https://github.com/opentelekomcloud-docs/image-management-service/blob/main/umn/source/managing_private_images/converting_the_image_format_using_qemu-img-hw.rst

broken URL: https://obs-20181128.ims.obs.eu-de.otc.t-systems.com/DT-image-convert-tools.zip

BR Thies

**Comment by mpristro** [comment]
Thank you for your report, ticket OCS-8940 was raised based on it. 
We will inform you after the update.

**Comment by mpristro** [comment]
.
